# Generated by Django 3.2.9 on 2022-09-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunchmap', '0002_shop_deadline_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea_id', models.IntegerField(blank=True, default=0, null=True, verbose_name='')),
                ('txt', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='idea_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=''),
        ),
    ]
