# Generated by Django 3.2.9 on 2022-09-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunchmap', '0004_auto_20220925_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='address',
        ),
        migrations.AddField(
            model_name='shop',
            name='txt',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
