# Generated by Django 3.2.9 on 2022-09-25 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunchmap', '0005_auto_20220925_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='txt',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='author',
        ),
    ]
